version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    volumes:
      - pgdata:/var/lib/postgresql/data

  createdb:
    build:
      context: .
    command: python create_db.py
    depends_on:
      - postgres

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - createdb

volumes:
  pgdata: